name: Update "Code review" project board on review requested.

on:
  pull_request:
    types:
      - review_requested
env:
  gh_app_ID: ${{ secrets.GH_APP_ID }}
  gh_app_installation_ID: ${{ secrets.GH_APP_INSTALLATION_ID }}
  gh_app_secret_key: ${{ secrets.GH_APP_SECRET_KEY }}
  organization: 'unico-it'
  project_id: 1
  status_waiting_for_review: "In review"

jobs:
  pull_request_review_requested:
    name: pull_request_review_requested
    runs-on: ubuntu-latest
    steps:
      - name: Move status to ${{ env.status_waiting_for_review }}
        uses: leonsteinhaeuser/project-beta-automations@939000fb1900c9fc4f7b5058a09d9f833ebc6859 # v2.2.1
        with:
          gh_app_ID: ${{ env.gh_app_ID }}
          gh_app_installation_ID: ${{ env.gh_app_installation_ID }}
          gh_app_secret_key: ${{ env.gh_app_secret_key }}
          organization: ${{ env.organization }}
          project_id: ${{ env.project_id }}
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: ${{ env.status_waiting_for_review }}
